export enum DAYS {
  TODAY = "Today",
  TOMORROW = "Tomorrow",
  YESTERDAY = "Yesterday",
}

export const teamAbbrvToLocation: Record<string, string> = {
  ANA: "Anaheim",
  BOS: "Boston",
  BUF: "Buffalo",
  CGY: "Calgary",
  CAR: "Carolina",
  CHI: "Chicago",
  COL: "Colorado",
  CBJ: "Columbus",
  DAL: "Dallas",
  DET: "Detroit",
  EDM: "Edmonton",
  FLA: "Sunrise",
  LAK: "Los Angeles",
  MIN: "Minnesota",
  MTL: "Montréal",
  NSH: "Nashville",
  NJD: "New Jersey",
  NYI: "New York",
  NYR: "New York",
  OTT: "Ottawa",
  PHI: "Philadelphia",
  PIT: "Pittsburgh",
  SJS: "San Jose",
  SEA: "Seattle",
  STL: "St. Louis",
  TBL: "Tampa Bay",
  TOR: "Toronto",
  UTA: "Utah",
  VAN: "Vancouver",
  VGK: "Vegas",
  WSH: "Washington",
  WPG: "Winnipeg",
};
